version: '1.0'
name: python-build
displayName: python_build
stages:
  - stage: 
    name: compile
    displayName: 编译
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands: 
          - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - pip3 install -r requirements.txt
          - python3 ./main.py
     
triggers:
  push:
    branches:
      include:
        - master
